make all:
	g++ --std=c++11 -lOpenCL LexRisLogicHeaders/LexRisLogic/src/FileStream.cpp LexRisLogicHeaders/LexRisLogic/src/StringSplitter.cpp LexRisLogicHeaders/LexRisLogic/src/Convert.cpp main.cpp -o main
